spring:
  application:
    name: plataforma-soporte-bancario
  rabbitmq:
    host: ${APP_RABBITMQ_HOST:localhost}
    port: ${APP_RABBITMQ_PORT:5672}
    username: ${APP_RABBITMQ_USERNAME:proyecto2027}
    password: ${APP_RABBITMQ_PASSWORD:proyecto2027}
  datasource:
    url: ${APP_DATASOURCE_URL:jdbc:postgresql://localhost:5432/proyecto2027}
    username: ${APP_DATASOURCE_USERNAME:proyecto2027}
    password: ${APP_DATASOURCE_PASSWORD:proyecto2027}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  outbox:
    relay:
      enabled: ${APP_OUTBOX_RELAY_ENABLED:true}
      fixed-delay-ms: ${APP_OUTBOX_RELAY_FIXED_DELAY_MS:5000}

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      service: ${spring.application.name}
  tracing:
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
