global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: secure-api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8080
        labels:
          service: secure-api-gateway

  - job_name: plataforma-soporte-bancario
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8081
        labels:
          service: plataforma-soporte-bancario

  - job_name: event-driven-notification-hub
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8083
        labels:
          service: event-driven-notification-hub
